# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CS M117' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  # Pods for CS M117
 pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'FirebaseUI/Auth'
  pod 'Firebase/Database'

end
